apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lalvarez-lang/PedidosApi'
    targetRevision: HEAD
    path: charts/pedido-app 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: DemoApi
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 