version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pedidosdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    ports:
      - "5050:80" 
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db 

volumes:
  postgres_data:
  pgadmin-data: