apiVersion: v2
name: DemoApi
description: A Helm chart for Kubernetes and PostrgresSQL
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
appVersion: "1.16.0"
