image:
  repository: DemoApi
  tag: latest

postgresql:
  postgresqlUsername: Admin
  postgresqlPassword: Admin123*
  postgresqlDatabase: PedidosDB 
  service:
    enabled: true
    type: ClusterIP

replicaCount: 2

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi