apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '<tu-repo-git>'
    targetRevision: HEAD
    path: charts/pedido-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: <tu-namespace>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 