apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: demo-api   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: aksdemo2025registry.azurecr.io/demo-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: demo-api-v
                  key: connectionstring
