apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data:
  postgresql-username: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}