name: CI
on:
  pull_request:
    branches:
      - develop
      - master
      - release
      - main
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Configurar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restaurar dependencias
        run: dotnet restore
      - name: Compilar
        run: dotnet build --configuration Release --no-restore
      # - name: Ejecutar pruebas
      #   run: dotnet test --configuration Release --no-build --verbosity normal


